name: build image and push to docker hub
on: push

jobs:
    npm-build:
        name: npm-build job
        runs-on: ubuntu-latest
        
        steps:
        - name: read repo content
          uses: actions/checkout@v4
        
        - name: login DockerHub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_TOKEN }}
            
        - name: build and push to docker hub
          uses: docker/build-push-action@v5
          with:
            push: true
            tags: ludi888/react-app:latest
       