name: build React project
on: push

jobs:
    npm-build:
        name: npm-build job
        runs-on: ubuntu-latest
        
        steps:
        - name: read repo content
          uses: actions/checkout@v4
        
        - name: install dependency
          run: npm install
        
        - name: build project
          run: npm run build
            